# Generated by Django 4.0.4 on 2022-04-26 08:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
